Repository paulsengroup/StripePy, pull requests merged in 2024-11, with the labels that each got.

#18 Bug removal: nan is not equal to nan
  src/stripepy/utils/stripe.py
Labels: bug

#20 Fix error in CLI parsing logic
  src/stripepy/cli/setup.py
Labels: bug

#21 Add mock CLI tests to the CI pipeline
  .github/workflows/ci.yml
Labels: bug

#22 Implement stripepy download
  src/stripepy/cli/download.py
  src/stripepy/cli/setup.py
  src/stripepy/main.py
Labels: enhancement, testing

#26 Adjust path to output folder
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/cli/setup.py
  test/test_IO.py
Labels: refactor

#23 Refactoring/step1
  src/stripepy/stripepy.py
  src/stripepy/utils/stripe.py
  test/test_stripepy.py
Labels: testing, refactor

#24 Refactoring/step2
  src/stripepy/stripepy.py
  src/stripepy/utils/TDA.py
  src/stripepy/utils/finders.py
  src/stripepy/utils/persistence1d.py
  src/stripepy/utils/regressions.py
Labels: testing, refactor

#25 Refactor Stripe class
  src/stripepy/stripepy.py
  src/stripepy/utils/postprocessing.py
  src/stripepy/utils/stripe.py
Labels: enhancement, testing, refactor

#29 Stripe class: expose seed and topological persistence as attributes
  src/stripepy/utils/stripe.py
Labels: bug

#28 Fix validation logic in _output_dir_checked()
  src/stripepy/cli/setup.py
Labels: bug

#30 Fix datarace when plotting using multiprocessing
  src/stripepy/IO.py
  src/stripepy/main.py
  src/stripepy/stripepy.py
  src/stripepy/utils/evaluate.py
  src/stripepy/utils/finders.py
Labels: bug

#31 Add --nproc to stripepy call
  src/stripepy/cli/call.py
  src/stripepy/cli/setup.py
  src/stripepy/stripepy.py
  src/stripepy/utils/finders.py
Labels: enhancement

#38 Add Dockerfile
  .dockerignore
  Dockerfile
  utils/devel/build_dockerfile.sh
Labels: enhancement, dependencies

#36 Add SPDX header to all source files
  .editorconfig
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  README.md
  pyproject.toml
  src/__init__.py
  src/stripepy/IO.py
  src/stripepy/__init__.py
  src/stripepy/cli/call.py
  src/stripepy/cli/setup.py
  src/stripepy/configs.py
  src/stripepy/main.py
  src/stripepy/main_over_MoDLE.py
  src/stripepy/others.py
  src/stripepy/stripepy.py
  src/stripepy/utils/TDA.py
  src/stripepy/utils/__init__.py
  src/stripepy/utils/evaluate.py
  src/stripepy/utils/finders.py
  src/stripepy/utils/persistence1d.py
  src/stripepy/utils/postprocessing.py
  src/stripepy/utils/regressions.py
  src/stripepy/utils/stripe.py
  src/stripepy/utils/unionfind.py
  test/test_IO.py
  test/test_others.py
  test/test_stripepy.py
Labels: enhancement

#33 Restructure output HDF5 file layout
  src/stripepy/cli/call.py
  src/stripepy/stripepy.py
Labels: enhancement

#32 Run stripepy call as part of the CI pipeline
  .github/workflows/ci.yml
  src/stripepy/cli/download.py
  test/scripts/generate_test_matrix.py
Labels: enhancement, testing

#39 Refuse to process files with non-uniform bin sizes
  src/stripepy/others.py
Labels: enhancement

#40 Add GHA workflow to build StripePy's Dockerfile
  .github/workflows/build-dockerfile.yml
  utils/devel/build_dockerfile.sh
  utils/devel/test_docker_image.sh
Labels: enhancement

#42 Automate StripePy packaging
  .github/workflows/build-dockerfile.yml
  .github/workflows/build-package.yml
  Dockerfile
  pyproject.toml
Labels: enhancement

#61 Remove flag glob-pers-type
  .github/workflows/ci.yml
  src/stripepy/cli/call.py
  src/stripepy/cli/setup.py
  src/stripepy/main_over_MoDLE.py
  src/stripepy/stripepy.py
  utils/devel/test_docker_image.sh
Labels: documentation, refactor
