Repository paulsengroup/StripePy, pull requests merged in 2024-12, with the labels that each got.

#62 Officially support Python 3.13
  .github/workflows/build-dockerfile.yml
  .github/workflows/build-package.yml
  .github/workflows/ci.yml
  pyproject.toml
  src/stripepy/utils/evaluate.py
Labels: dependencies, testing

#63 Remove unnecessary files
  src/stripepy/IO.py
  src/stripepy/configs.py
  src/stripepy/main_over_MoDLE.py
  src/stripepy/stripepy.py
  src/stripepy/utils/evaluate.py
Labels: refactor

#67 Update the test datasets
  .github/workflows/build-dockerfile.yml
  .github/workflows/ci.yml
  src/stripepy/cli/download.py
  utils/devel/test_docker_image.sh
Labels: enhancement, testing

#64 Initial implementation of StripePy integration test suite
  .github/workflows/ci.yml
  Dockerfile
  pyproject.toml
  src/stripepy/cli/call.py
  src/stripepy/cli/setup.py
  src/stripepy/cli/view.py
  src/stripepy/main.py
  src/stripepy/utils/finders.py
  test/README.md
  test/integration/test_stripepy_call.py
  test/integration/test_stripepy_download.py
  test/integration/test_stripepy_view.py
  test/unit/test_IO.py
  test/unit/test_others.py
  test/unit/test_stripepy.py
Labels: enhancement, testing

#44 Collect test coverage information
  .github/.codecov.yml
  .github/workflows/ci.yml
  pyproject.toml
Labels: testing

#69 Set default parameters
  src/stripepy/cli/setup.py
Labels: parameters

#59 Update the README with installation instructions and a basic walkthrough
  README.md
  docs/assets/4DNFI9GMP2J8_chr2_156mbp_higlass_view.png
Labels: documentation, enhancement

#73 Remove redundant __init__.py
  src/__init__.py
  src/stripepy/utils/__init__.py
Labels: enhancement

#71 Rework StripePy IO
  .dockerignore
  .github/workflows/build-dockerfile.yml
  .github/workflows/ci.yml
  Dockerfile
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/cli/view.py
  src/stripepy/stripepy.py
  src/stripepy/utils/finders.py
  test/README.md
  test/unit/__init__.py
  test/unit/common/cool.py
  test/unit/common/data.py
  test/unit/test_IO.py
  test/unit/test_others.py
Labels: enhancement, refactor

#76 Initial implementation of stripepy plot
  .github/workflows/build-dockerfile.yml
  .github/workflows/ci.yml
  .gitignore
  README.md
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/setup.py
  src/stripepy/main.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/common.py
  test/README.md
  test/integration/test_stripepy_call.py
  test/integration/test_stripepy_download.py
  test/integration/test_stripepy_plot.py
  test/integration/test_stripepy_view.py
  test/scripts/generate_test_figures.sh
  test/unit/test_others.py
Labels: enhancement

#81 Update the README
  README.md
Labels: documentation
