Repository paulsengroup/StripePy, pull requests merged in 2025-01, with the labels that each got.

#27 Setup application logging
  pyproject.toml
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/setup.py
  src/stripepy/main.py
  src/stripepy/others.py
  src/stripepy/stripepy.py
Labels: enhancement

#83 Improve error messages issued upon failure of CLI argument type validation
  src/stripepy/cli/setup.py
Labels: enhancement

#86 [feature]: add dynamic progress bar
  pyproject.toml
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/common.py
Labels: enhancement

#84 [refactor] rewrite stripepy call to use the new plotting functions
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/main.py
  src/stripepy/others.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/finders.py
  test/unit/test_IO.py
  test/unit/test_others.py
Labels: enhancement, refactor

#87 [refactor] update stripepy plot to use the new plot API
  src/stripepy/IO.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/stripe.py
  test/integration/test_stripepy_download.py
Labels: enhancement, refactor

#88 [dependencies] remove unused dependency and reduce number of core dependencies
  .github/workflows/ci.yml
  Dockerfile
  README.md
  pyproject.toml
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/view.py
  src/stripepy/main.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/common.py
  src/stripepy/utils/progress_bar.py
  test/integration/__init__.py
  test/integration/common.py
  test/integration/test_stripepy_call.py
  test/integration/test_stripepy_plot.py
Labels: enhancement, dependencies

#93 Correct bug in file name inside _plot_stripes_helper
  src/stripepy/stripepy.py
Labels: bug

#94 Fix bug when running stripepy-call --unit-test
  src/stripepy/cli/download.py
Labels: bug

#95 Simplify CI by adding the "minimal_install" param to the job matrix
  .github/workflows/ci.yml
Labels: enhancement, testing, refactor

#96 Address CodeQL warnings
  .github/workflows/build-dockerfile.yml
  .github/workflows/build-package.yml
  .github/workflows/cache-test-datasets.yml
  .github/workflows/ci.yml
  .github/workflows/lint-cff.yml
Labels: enhancement

#92 [bug] Fix inconsistent results produced on different platforms
  src/stripepy/cli/download.py
  src/stripepy/cli/view.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/TDA.py
  src/stripepy/utils/common.py
  src/stripepy/utils/persistence1d.py
  test/integration/common.py
  test/integration/test_stripepy_call.py
  test/integration/test_stripepy_download.py
Labels: bug

#91 [performance]: optimize find_HIoIs()
  src/stripepy/stripepy.py
  src/stripepy/utils/finders.py
  src/stripepy/utils/regressions.py
Labels: enhancement

#97 [refactor]: restructure stripepy call outputs
  .github/.codecov.yml
  .github/workflows/build-dockerfile.yml
  README.md
  benchmark/run-over-StripeBench.py
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/setup.py
  src/stripepy/cli/view.py
  src/stripepy/main.py
  src/stripepy/stripepy.py
  test/integration/test_stripepy_call.py
  test/unit/test_IO.py
  utils/devel/test_docker_image.sh
Labels: enhancement, refactor

#99 Add reference to StripeBench
  benchmark/run-over-StripeBench.py
Labels: documentation

#98 [refactor]: remove unused code
  src/stripepy/IO.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/view.py
  src/stripepy/others.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils/postprocessing.py
Labels: refactor

#102 Simplify assertion for neighborhood size
  src/stripepy/stripepy.py
Labels: refactor

#115 [docs]: update README with note regarding documentation versioning
  README.md
Labels: documentation

#114 [ci]: bump actions
  .github/workflows/build-dockerfile.yml
  .github/workflows/build-package.yml
  .github/workflows/ci.yml
Labels: testing

#116 [bug]: fix off-by-one error in code computing stripe biodescriptors
  .github/workflows/build-dockerfile.yml
  .github/workflows/ci.yml
  src/stripepy/cli/download.py
  src/stripepy/utils/stripe.py
  test/integration/test_stripepy_download.py
  test/integration/test_stripepy_view.py
Labels: bug
