Repository paulsengroup/StripePy, pull requests merged in 2025-07, with the labels that each got.

#162 [feature]: add CLI options to display Stripepy's license and bibtex entry
  src/stripepy/cli/setup.py
  src/stripepy/main.py
  test/integration/test_stripepy_cli.py
Labels: documentation, enhancement

#60 Add documentation
  docs/Makefile
  docs/README.md
  docs/api.rst
  docs/assets/4DNFI9GMP2J8_chr14_34mbp-cm_plot_highlight_stripes.pdf
  docs/assets/4DNFI9GMP2J8_chr14_34mbp-cm_plot_highlight_stripes.png
  docs/assets/4DNFI9GMP2J8_chr2_156mbp_higlass_view.pdf
  docs/cli_reference.rst
  docs/conf.py
  docs/detect_stripes.rst
  docs/downloading_sample_datasets.rst
  docs/fetch_stripes.rst
  docs/generate_cli_reference.py
  docs/generate_plots.rst
  docs/index.rst
  docs/installation.rst
  docs/quickstart.rst
  docs/requirements.txt
  docs/visualize_stripes.rst
  src/stripepy/data_structures/result.py
  src/stripepy/data_structures/result_file.py
Labels: documentation

#165 Restructure README
  CITATION.cff
  README.md
  pipeline-short.jpeg
Labels: documentation

#166 [docs]: move pipeline-short.jpeg under docs/assets
  README.md
  docs/assets/pipeline-short.jpeg
Labels: documentation

#167 [maintenance]: update pyproject.toml
  pyproject.toml
Labels: enhancement, refactor

#168 [feature]: initial support for telemetry collection
  docs/assets/telemetry_table.tsv
  docs/index.rst
  docs/telemetry.rst
  pyproject.toml
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/telemetry.py
  src/stripepy/cli/view.py
  src/stripepy/data_structures/result_file.py
  src/stripepy/main.py
  test/integration/common.py
  test/integration/test_stripepy_call.py
  test/integration/test_stripepy_cli.py
  test/integration/test_stripepy_download.py
  test/integration/test_stripepy_plot.py
  test/integration/test_stripepy_view.py
  utils/devel/test_docker_image.sh
Labels: enhancement

#170 [deps]: update pyproject.toml to include a [doc] option group
  .readthedocs.yaml
  docs/README.md
  docs/requirements.txt
  pyproject.toml
Labels: documentation, dependencies
