Repository paulsengroup/StripePy, pull requests merged in 2025-02, with the labels that each got.

#120 [feature]: re-introduce progress bars
  src/stripepy/IO.py
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/logging.py
  src/stripepy/main.py
  src/stripepy/utils/common.py
  src/stripepy/utils/progress_bar.py
Labels: enhancement

#118 [feature] show default values when calling stripepy ... --help
  src/stripepy/cli/setup.py
Labels: enhancement

#125 [bug]: correct bound checking in stripe plotting code
  src/stripepy/plot.py
  src/stripepy/stripepy.py
Labels: bug

#126 Fixed exception due to missing folders in run-over-StripeBench
  benchmark/run-over-StripeBench.py
Labels: bug

#127 [bug]: fix handling of chromosomes without stripes
  src/stripepy/IO.py
  src/stripepy/cli/logging.py
  src/stripepy/stripepy.py
Labels: bug

#128 Add nproc flag to benchmark/run-over-StripeBench.py
  benchmark/run-over-StripeBench.py
Labels: enhancement

#131 [deps]: bump dependencies
  .github/workflows/build-dockerfile.yml
  .github/workflows/lint-cff.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies

#123 [bug]: fix k-neighborhood definition in compute_biodescriptors
  .dockerignore
  .github/workflows/build-dockerfile.yml
  .github/workflows/ci.yml
  Dockerfile
  benchmark/run-over-StripeBench.py
  pyproject.toml
  src/stripepy/IO.py
  src/stripepy/cli/download.py
  src/stripepy/cli/setup.py
  src/stripepy/stripepy.py
  src/stripepy/utils/stripe.py
  test/README.md
  test/integration/test_stripepy_call.py
  test/integration/test_stripepy_download.py
  test/integration/test_stripepy_plot.py
  test/integration/test_stripepy_view.py
  test/scripts/generate_reference_tables.sh
  test/scripts/generate_test_figures.sh
  test/scripts/result_file_to_parquet.py
  test/unit/test_IO.py
  test/unit/test_stripe.py
  utils/devel/test_docker_image.sh
Labels: bug, enhancement

#132 [refactor]: rework project layout
  pyproject.toml
  src/stripepy/algorithms/finders.py
  src/stripepy/algorithms/regressions.py
  src/stripepy/algorithms/step1.py
  src/stripepy/algorithms/step2.py
  src/stripepy/algorithms/step3.py
  src/stripepy/algorithms/step4.py
  src/stripepy/algorithms/step5.py
  src/stripepy/cli/call.py
  src/stripepy/cli/download.py
  src/stripepy/cli/plot.py
  src/stripepy/cli/setup.py
  src/stripepy/cli/view.py
  src/stripepy/data_structures/__init__.py
  src/stripepy/data_structures/concurrent.py
  src/stripepy/data_structures/persistence1d.py
  src/stripepy/data_structures/result.py
  src/stripepy/data_structures/result_file.py
  src/stripepy/data_structures/shared_sparse_matrix.py
  src/stripepy/data_structures/stripe.py
  src/stripepy/data_structures/unionfind.py
  src/stripepy/io/__init__.py
  src/stripepy/io/common.py
  src/stripepy/io/logging.py
  src/stripepy/io/progress_bar.py
  src/stripepy/main.py
  src/stripepy/others.py
  src/stripepy/plot.py
  src/stripepy/stripepy.py
  src/stripepy/utils.py
  test/integration/common.py
  test/scripts/compare_result_files.py
  test/scripts/result_file_to_parquet.py
  test/unit/conftest.py
  test/unit/test_algorithms/test_step1.py
  test/unit/test_data_structures/test_result.py
  test/unit/test_data_structures/test_result_file.py
  test/unit/test_data_structures/test_stripe.py
  test/unit/test_helpers/test_helpers_cool.py
  test/unit/test_helpers/test_helpers_data.py
  test/unit/test_io/test_common.py
  test/unit/test_utils.py
Labels: refactor
